name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false

      - name: Lint
        run: npm run lint --silent

      - name: Test (with flaky retry)
        env:
          # Ensure vite/vitest have sane defaults in test mode
          VITE_SUPABASE_URL: http://localhost
          VITE_SUPABASE_ANON_KEY: test_key
        run: npm test --silent -- --retry=2

  preview-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false

      - name: Build (preview)
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL || 'https://example.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY || 'anon-key-placeholder' }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-dist
          path: dist
          if-no-files-found: error

  e2e:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build app for preview
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL || 'https://example.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY || 'anon-key-placeholder' }}
          VITE_SKIP_AUTH: 'true'
          VITE_SKIP_RBAC: 'true'
      - name: Run Playwright tests
        env:
          E2E_BASE_URL: http://localhost:4173
          E2E_SKIP_AUTH: 'true'
        run: npx playwright test

      - name: Upload Playwright raw results (traces, videos, screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
          retention-days: 7

      - name: Upload Playwright blob report (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-blob-report
          path: blob-report
          if-no-files-found: ignore
          retention-days: 7
